version: 0.0
os: ubuntu
files:
  - source: /
    destination: /usr/app
hooks:
  BeforeInstall:
    - location: scripts/Before_Install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/After_Install.sh
      timeout: 300
      runas: root

