name: Deploy to Amazon EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Docker Login
        run:
          docker login -u wenzellopes -p Darth@31101998
      - name: Docker Push
        run: |
          docker image build -t docker-chat-final:latest .
          docker tag docker-chat-final:latest wenzellopes/docker-chat
          docker push wenzellopes/docker-chat:latest  
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.PEM  }}
          HOSTNAME : ${{ secrets.HOST_DNS  }}
          USER_NAME : ${{ secrets.USER_EC2  }}
        run: |          
          docker login -u wenzellopes -p Darth@31101998
          docker pull wenzellopes/docker-chat
          docker stop gifted_khorana
          docker run -d -p 3000:3000 wenzellopes/docker-chat



   
